version: '3.8'

services:
  # Nginx 리버스 프록시
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx

    container_name: hospital-area-nginx

    # 포트 매핑: 외부 80번 → 내부 80번
    ports:
      - "80:80"

    # FastAPI 서비스와 연결
    depends_on:
      - web

    # 볼륨 마운트 (정적 파일 실시간 반영)
    volumes:
      - ./static:/usr/share/nginx/html/static:ro  # 읽기 전용
      - ./nginx.conf:/etc/nginx/nginx.conf:ro     # 읽기 전용

    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/nginx-health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

    networks:
      - app-network

  # FastAPI 백엔드
  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: hospital-area-analysis

    # 포트 노출 (외부 접근 불가, Nginx를 통해서만 접근)
    expose:
      - "8000"

    # 환경 변수 파일 로드
    env_file:
      - .env

    # 볼륨 마운트 (개발 편의성)
    volumes:
      - ./static:/app/static
      - ./server.py:/app/server.py
      - ./index.html:/app/index.html

    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    networks:
      - app-network

# 네트워크 설정
networks:
  app-network:
    driver: bridge
